package modelo;
// Generated 28/06/2015 01:18:53 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ciclo generated by hbm2java
 */
@Entity
@Table(name="ciclo"
    ,catalog="tesisproduccion2"
)
public class Ciclo  implements java.io.Serializable {


     private Integer idciclo;
     private String nombre;
     private Date fechainicio;
     private Date fechafin;
     private Set cursos = new HashSet(0);

    public Ciclo() {
    }

	
    public Ciclo(String nombre, Date fechainicio, Date fechafin) {
        this.nombre = nombre;
        this.fechainicio = fechainicio;
        this.fechafin = fechafin;
    }
    public Ciclo(String nombre, Date fechainicio, Date fechafin, Set cursos) {
       this.nombre = nombre;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.cursos = cursos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idciclo", unique=true, nullable=false)
    public Integer getIdciclo() {
        return this.idciclo;
    }
    
    public void setIdciclo(Integer idciclo) {
        this.idciclo = idciclo;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechainicio", nullable=false, length=10)
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechafin", nullable=false, length=10)
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ciclo")
    public Set getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }




}


