package modelo;
// Generated 28/06/2015 01:18:53 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name="curso"
    ,catalog="tesisproduccion2"
)
public class Curso  implements java.io.Serializable {


     private Integer idcurso;
     private Ciclo ciclo;
     private Nivel nivel;
     private String nombre;
     private String descripcion;
     private String observacion;
     private Set usuarioCursos = new HashSet(0);

    public Curso() {
    }

	
    public Curso(Ciclo ciclo, Nivel nivel, String nombre) {
        this.ciclo = ciclo;
        this.nivel = nivel;
        this.nombre = nombre;
    }
    public Curso(Ciclo ciclo, Nivel nivel, String nombre, String descripcion, String observacion, Set usuarioCursos) {
       this.ciclo = ciclo;
       this.nivel = nivel;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.observacion = observacion;
       this.usuarioCursos = usuarioCursos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcurso", unique=true, nullable=false)
    public Integer getIdcurso() {
        return this.idcurso;
    }
    
    public void setIdcurso(Integer idcurso) {
        this.idcurso = idcurso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ciclo_idciclo", nullable=false)
    public Ciclo getCiclo() {
        return this.ciclo;
    }
    
    public void setCiclo(Ciclo ciclo) {
        this.ciclo = ciclo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nivel_idnivel", nullable=false)
    public Nivel getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Nivel nivel) {
        this.nivel = nivel;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="observacion", length=45)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="curso")
    public Set getUsuarioCursos() {
        return this.usuarioCursos;
    }
    
    public void setUsuarioCursos(Set usuarioCursos) {
        this.usuarioCursos = usuarioCursos;
    }




}


