package modelo;
// Generated 28/06/2015 01:18:53 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DetalleLeccion generated by hbm2java
 */
@Entity
@Table(name="detalle_leccion"
    ,catalog="tesisproduccion2"
)
public class DetalleLeccion  implements java.io.Serializable {


     private Integer iddetalleleccion;
     private int numeropregunta;
     private String pregunta;
     private String respuesta;
     private String observacion;
     private String mensaje;
     private Set leccions = new HashSet(0);
     private Set vocabularios = new HashSet(0);

    public DetalleLeccion() {
    }

	
    public DetalleLeccion(int numeropregunta, String pregunta, String respuesta, String observacion, String mensaje) {
        this.numeropregunta = numeropregunta;
        this.pregunta = pregunta;
        this.respuesta = respuesta;
        this.observacion = observacion;
        this.mensaje = mensaje;
    }
    public DetalleLeccion(int numeropregunta, String pregunta, String respuesta, String observacion, String mensaje, Set leccions, Set vocabularios) {
       this.numeropregunta = numeropregunta;
       this.pregunta = pregunta;
       this.respuesta = respuesta;
       this.observacion = observacion;
       this.mensaje = mensaje;
       this.leccions = leccions;
       this.vocabularios = vocabularios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iddetalleleccion", unique=true, nullable=false)
    public Integer getIddetalleleccion() {
        return this.iddetalleleccion;
    }
    
    public void setIddetalleleccion(Integer iddetalleleccion) {
        this.iddetalleleccion = iddetalleleccion;
    }

    
    @Column(name="numeropregunta", nullable=false)
    public int getNumeropregunta() {
        return this.numeropregunta;
    }
    
    public void setNumeropregunta(int numeropregunta) {
        this.numeropregunta = numeropregunta;
    }

    
    @Column(name="pregunta", nullable=false, length=100)
    public String getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }

    
    @Column(name="respuesta", nullable=false, length=100)
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }

    
    @Column(name="observacion", nullable=false, length=100)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    
    @Column(name="mensaje", nullable=false, length=45)
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="detalleLeccion")
    public Set getLeccions() {
        return this.leccions;
    }
    
    public void setLeccions(Set leccions) {
        this.leccions = leccions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="detalleLeccion")
    public Set getVocabularios() {
        return this.vocabularios;
    }
    
    public void setVocabularios(Set vocabularios) {
        this.vocabularios = vocabularios;
    }




}


