package modelo;
// Generated 28/06/2015 01:18:53 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Formulario generated by hbm2java
 */
@Entity
@Table(name="formulario"
    ,catalog="tesisproduccion2"
)
public class Formulario  implements java.io.Serializable {


     private Integer idformulario;
     private Usuariofac usuariofac;
     private String titulo;
     private String mensaje;

    public Formulario() {
    }

    public Formulario(Usuariofac usuariofac, String titulo, String mensaje) {
       this.usuariofac = usuariofac;
       this.titulo = titulo;
       this.mensaje = mensaje;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idformulario", unique=true, nullable=false)
    public Integer getIdformulario() {
        return this.idformulario;
    }
    
    public void setIdformulario(Integer idformulario) {
        this.idformulario = idformulario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuariofac_idusuariofac", nullable=false)
    public Usuariofac getUsuariofac() {
        return this.usuariofac;
    }
    
    public void setUsuariofac(Usuariofac usuariofac) {
        this.usuariofac = usuariofac;
    }

    
    @Column(name="titulo", nullable=false, length=100)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    
    @Column(name="mensaje", nullable=false, length=300)
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }




}


