package modelo;
// Generated 28/06/2015 01:18:53 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuariofac generated by hbm2java
 */
@Entity
@Table(name="usuariofac"
    ,catalog="tesisproduccion2"
)
public class Usuariofac  implements java.io.Serializable {


     private Integer idusuariofac;
     private Usuario usuario;
     private String user;
     private String pass;
     private String gradoAcademico;
     private String escuela;
     private Set formularios = new HashSet(0);
     private Set historialNotases = new HashSet(0);
     private Set usuarioCursos = new HashSet(0);

    public Usuariofac() {
    }

	
    public Usuariofac(Usuario usuario, String user, String pass, String escuela) {
        this.usuario = usuario;
        this.user = user;
        this.pass = pass;
        this.escuela = escuela;
    }
    public Usuariofac(Usuario usuario, String user, String pass, String gradoAcademico, String escuela, Set formularios, Set historialNotases, Set usuarioCursos) {
       this.usuario = usuario;
       this.user = user;
       this.pass = pass;
       this.gradoAcademico = gradoAcademico;
       this.escuela = escuela;
       this.formularios = formularios;
       this.historialNotases = historialNotases;
       this.usuarioCursos = usuarioCursos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idusuariofac", unique=true, nullable=false)
    public Integer getIdusuariofac() {
        return this.idusuariofac;
    }
    
    public void setIdusuariofac(Integer idusuariofac) {
        this.idusuariofac = idusuariofac;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_idusuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="user", nullable=false, length=45)
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }

    
    @Column(name="pass", nullable=false, length=45)
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }

    
    @Column(name="grado_academico", length=45)
    public String getGradoAcademico() {
        return this.gradoAcademico;
    }
    
    public void setGradoAcademico(String gradoAcademico) {
        this.gradoAcademico = gradoAcademico;
    }

    
    @Column(name="escuela", nullable=false, length=45)
    public String getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(String escuela) {
        this.escuela = escuela;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuariofac")
    public Set getFormularios() {
        return this.formularios;
    }
    
    public void setFormularios(Set formularios) {
        this.formularios = formularios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuariofac")
    public Set getHistorialNotases() {
        return this.historialNotases;
    }
    
    public void setHistorialNotases(Set historialNotases) {
        this.historialNotases = historialNotases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuariofac")
    public Set getUsuarioCursos() {
        return this.usuarioCursos;
    }
    
    public void setUsuarioCursos(Set usuarioCursos) {
        this.usuarioCursos = usuarioCursos;
    }




}


